### PR TITLE
Repository Cleanup

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- ***[Disable Unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable Unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
<br>

- Add a delay between every download
  request as to not spam the API.

<br>
<br>

## ![Badge Changes]

- Sorted files

- Formatted README

- Added license badge

- Linked dependencies

- Basic code refactor

- Moved SFW / NSFW endpoints into `/Data/`

- Linked endpoints 

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Nekos.life-Downloader

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
@wolkix3 Could you please review this PR~

**Comment by wolkix3** [comment]
Oh yes thank you very much, been quite busy lately so I didn't really check GitHub

**Comment by ElectronicsArchiver** [comment]
Wow, I didn't expect you to see my ping that seen.
Thank you.

**Comment by ElectronicsArchiver** [comment]
@wolkix3 Btw, have you thought about making a GitHub profile page?

**Comment by wolkix3** [comment]
Honestly never did, but probably should do soon since I'll probably be more active on GitHub soon

**Comment by ElectronicsArchiver** [comment]
Cool.
Lemme know if you need help with it~

This might come in handy:
https://github.com/MarkedDown

**Pull request merged**
